[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v6.0.0"
hooks = [
    { id = "check-yaml" },
    { id = "end-of-file-fixer" }
]

[[repos]]
repo = "local"

[[repos.hooks]]
id = "rustfmt"
name = "cargo rustfmt"
language = "system"
entry = "cargo"
args = ["fmt", "--all"]
pass_filenames = false
stages = ["pre-commit"]

[[repos.hooks]]
id = "i18n-unused"
name = "check unused i18n strings (warning only)"
language = "system"
entry = "pnpm"
args = ["run", "i18n:unused", "--warn-only"]
pass_filenames = false
always_run = true
verbose = true
stages = ["pre-commit"]
